apiVersion: v1
kind: Service
metadata:
  name: app-about-to-fail-service
spec:
  selector:
    app: app-about-to-fail
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-about-to-fail
spec:
  selector:
    matchLabels:
      app: app-about-to-fail
  replicas: 4
  template:
    metadata:
      labels:
        app: app-about-to-fail
    spec:
      containers:
        - name: app-about-to-fail
          image: 090841905266.dkr.ecr.eu-central-1.amazonaws.com/clusterabouttofail:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000